@host = http://localhost:8083

GET {{host}}/api/auth_user
Authorization: Bearer ATlYiRQEgeX9EiFFdXVM0jeJhMYByqB0pQ9D8OshsnIm1dGceMGgDJhbwCRY5to9oFXo487sxLRMS8mpq3WvR

###
POST {{host}}/api/login
Content-Type: application/json

{
    "email": "john@example.org"
}

###
POST {{host}}/api/users
Content-Type: application/json

{
    "email": "jane@example.org",
    "username": "jane"
}

###
POST {{host}}/api/users/jane/toggle_follow
Authorization: Bearer ATlZ47P0czLEJu9Ya5le5IB4eaRxDgZjAcCxHDaMdDRBiGOiAhyPGAhOpmdlb9U2o6bNkiXO88pAT43mVkP48

### 
GET {{host}}/api/users/john 
Authorization: Bearer ATlcH535pmAxWV8zJJuTAFLLynXyWADVg48jzFgP5ouI4NLHStmFqC5rLCyNrpg0fw4SfJnmo0h0kmPcr43nK

###
GET {{host}}/api/users?search=john&first=1&after=1
Authorization: Bearer ATlcHjkgECYiGYKhauHps12exsgw0j00yi3VZLdhJDuZCWvmD0uV39BSQqjB6u8bkwfV0SrYSuvqLDkY8XrjG