@host = http://localhost:8083

GET {{host}}/api/auth_user
Authorization: Bearer ATlYiRQEgeX9EiFFdXVM0jeJhMYByqB0pQ9D8OshsnIm1dGceMGgDJhbwCRY5to9oFXo487sxLRMS8mpq3WvR

###
POST {{host}}/api/login
Content-Type: application/json

{
    "email": "john@example.org"
}

###
POST {{host}}/api/users
Content-Type: application/json

{
    "email": "jane@example.org",
    "username": "jane"
}

###
POST {{host}}/api/users/jane/toggle_follow
Authorization: Bearer ATlZ47P0czLEJu9Ya5le5IB4eaRxDgZjAcCxHDaMdDRBiGOiAhyPGAhOpmdlb9U2o6bNkiXO88pAT43mVkP48

### 
GET {{host}}/api/users/john 
Authorization: Bearer ATlZjfAOcyiaNjNN8Fh3C9Sslzs8B4JpiGlE59i3GxfmxrW31OxbF8P2b7MnMtInHbgVdPxXCoBd7iQQtltxX